#ifndef __INCLUDE_H
#define __INCLUDE_H



#include "stm32f10x_it.h"
#include "nvic.h"
#include "systick.h"
#include "led.h"
#include "key.h"
#include "ad5667.h"
//#include "ad9834.h"
//#include "key_exti.h"
//#include "UartMoni.h"
//#include "i2c_moni.h"
//#include "mpu6050_dmp_conf.h"
//#include "usart.h" 
//#include "dma_m2m.h"
//#include "dma_dst_uart.h"
//#include "dma_src_uart.h"
//#include "i2c_hard.h"
//#include "eeprom_i2cmoni.h"
//#include "dmp_exti.h"
//#include "spi.h"
//#include "flash_spi.h"
//#include "TIM_Base.h"
//#include "advance_tim.h"
//#include "general_tim.h"
//#include "smg.h"
//#include "beep.h"
//#include "oled_i2c.h"
//#include "oled_SSD1306_GT20L16.h"
//#include "oled_SSD1306_iic_8080.h"
//#include "codetab.h"
//#include "picture.h"
//#include "lcd_driver.h"
//#include "gui.h"
//#include "touch.h"
//#include "ov7725.h"
//#include "sccb.h"
//#include "dht11.h"
//#include "gpio.h"
//#include "ov7725_eagle.h"
//#include "st7735s_lcd.h"
//#include "st7735s_gui.h"
//#include "nrf24l01.h"
//#include "unpack.h"
//#incldue "oled_iic.h"
//#include "sd.h"
//#include <math.h>
//#include "ff.h"
//#include "diskio.h"
//#include "myfatapp.h"
//#include "mp3player.h"
//#include "vs10xx.h"
//#include "ili9341.h"
//#include "fonts.h"
//#include "adc.h"
//#include "tempad.h"
//#include "iwdg.h"
//#include "wwdg.h"
//#include "dac.h"
//#include "pvd.h"
//#include "pwr.h"
//#include "rtc.h"
//#include "date.h"
//#include "calendar.h"

#endif


